version: '3'


services:
    hugo_server:
        build:
          context: "."
          dockerfile: "./compose/hugo/Dockerfile"
        image: hugo_server_image
        command: server --noHTTPCache
        volumes:
          - "./new-site:/src"
        ports:
          - "1313:1313"

    tailwindcss:
        container_name: 'tailwindcss_container'
        build: .
        restart: unless-stopped
        ports:
            - '9000:9000'
        volumes:
            - './src:/var/www'
        working_dir: /var/www
        command: bash -c "npm install && npm run dev"
