version: '3'


services:
    hugo_server:
        container_name: 'hugo_server'
        build:
          context: "."
          dockerfile: "./compose/hugo/Dockerfile"
        command: server --noHTTPCache
        volumes:
          - "./new-site:/src"
        ports:
          - "1313:1313"

    tailwindcss:
        container_name: 'hugo_tailwindcss_container'
        build:
            context: "."
            dockerfile: "./compose/node/Dockerfile"
        restart: unless-stopped
        ports:
            - '9000:9000'
        volumes:
            - './tailwind:/var/www'
        working_dir: /var/www
        command: bash -c "npm install && npm run dev"
